"""Every shipped unit vendors the current helper, not the one it was built with.

A unit's `bin/` and `scripts/` hold build-time copies of repository sources, and
those copies are what an installed unit actually runs. Nothing compared them, so a
helper change could land in the repository and never reach a consumer: the non-open
link-only guard (`5f79a87db`) did exactly that, staying inert in all nine copies of
`perspicacite_kb_bind.py` while every bundle record carried the `license_tier` it
reads.

Only copies that share a filename with a repository source are compared. A unit
asset authored in place has no source to drift from — `bin/search_skills.py` and
`bin/semantic_search.py` are generated by `scripts/router_shape.py` from the
canonical selector, and `workflows/bin/semantic_search.py` is the historical copy
`docs/selection.md` and `USAGE.md` both document as outside that unification.
"""
import pathlib

ROOT = pathlib.Path(__file__).parent.parent
SOURCE_DIRS = ("scripts", "asb_skill_collections")
UNIT_GLOBS = ("collections/*/*/", "packs/*/*/")
BINDER = "perspicacite_kb_bind.py"


def _sources():
    out = {}
    for d in SOURCE_DIRS:
        for p in (ROOT / d).rglob("*.py"):
            if "__pycache__" not in p.parts:
                out.setdefault(p.name, []).append(p)
    return out


def _vendored():
    for glob in UNIT_GLOBS:
        for unit in sorted(ROOT.glob(glob)):
            for p in sorted(unit.rglob("*.py")):
                if "__pycache__" not in p.parts:
                    yield p


def test_there_is_something_to_check():
    names = {p.name for p in _vendored()} & set(_sources())
    assert BINDER in names, "no unit vendors the binder; this guard would be vacuous"


def test_every_vendored_copy_of_a_repository_source_is_current():
    sources = _sources()
    stale = []
    for p in _vendored():
        candidates = sources.get(p.name)
        if not candidates:
            continue
        if p.read_bytes() not in {c.read_bytes() for c in candidates}:
            stale.append(str(p.relative_to(ROOT)))
    assert not stale, f"stale vendored copy/copies: {stale}"
