name: Environment
slug: environment
evidence_spans:
- Environment – orchestrates interaction between the mass spectrometer and the controller.
derived_from:
- doi: 10.1021/acs.analchem.0c03895
  title: Rapid Development of Improved Data-Dependent Acquisition Strategies
schema_version: 0.2.0
techniques:
- LC-MS
- tandem-MS
